services:
    signdoc:
        container_name: signdoc
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile
        image: core-signdoc:latest
        ports:
            - 1712:1712
        volumes:
            - ./logs:/usr/local/signdoc/logs
            - ./docs:/usr/local/signdoc/docs
        environment:
            TZ: 'Asia/Jakarta'
            SPRING_APPLICATION_JSON: '{
            "server.port" : "1712",
            "spring.zipkin.baseUrl":"http://zipkin.zipkin.svc.cluster.local:9411/",
            "spring.sleuth.sampler.probability":1.0,
            "spring.zipkin.service.name":"signdoc",
            "spring.application.name":"signdoc",
            "spring.zipkin.sender.type":"web"
        }'
